/**
 * The Odoo configuration a validation run is given (ADR-027).
 *
 * Generated, never the customer's. Their `odoo.conf` holds `admin_passwd` and
 * `db_password`, and its `addons_path` points at the live addons directory - the
 * one the running server loads. A validation run must use neither: it works on
 * the workspace clone, and it authenticates as the platform's own validation
 * role.
 *
 * Reusing the customer's file would have been the obvious shortcut, and it would
 * have meant every test run held a superuser credential and could load the live
 * directory. This file is short because that shortcut was refused.
 */

export interface OdooConfInput {
  /** The runtime's own addons, from the core directory. */
  readonly coreAddonsPath: string;
  /** Shared directories for this series: enterprise, OCA, and so on. */
  readonly sharedAddonPaths: readonly string[];
  /**
   * The project's addons, from the task's workspace clone. Never the live
   * directory: validating the code the agent changed is the entire point.
   */
  readonly workspaceAddonsPath: string;
  readonly databaseName: string;
  readonly databaseHost: string;
  readonly databasePort: number;
  /** The platform's validation role. Not the customer's `odoo` user. */
  readonly databaseUser: string;
}

/**
 * Builds the file's contents.
 *
 * The password is deliberately absent. It is passed to the process through
 * `PGPASSWORD` in the environment for the life of that process, so it is never
 * written to a file that outlives the run or that another user on the host can
 * read.
 */
export function buildOdooConf(input: OdooConfInput): string {
  const addonsPath = [
    input.workspaceAddonsPath,
    ...input.sharedAddonPaths,
    input.coreAddonsPath,
  ].join(',');

  return [
    '[options]',
    '; Generated by LinkedERP for one validation run. Not the project configuration.',
    `addons_path = ${addonsPath}`,
    `db_host = ${input.databaseHost}`,
    `db_port = ${input.databasePort}`,
    `db_user = ${input.databaseUser}`,
    `db_name = ${input.databaseName}`,
    '; The database list is never exposed, and the database manager is unreachable.',
    'list_db = False',
    '; No demo data: it is large, slow, and its records are not the project.',
    'without_demo = all',
    '; No cron: a scheduled job firing during a test run is noise at best.',
    'max_cron_threads = 0',
    '; Single process, so a failure is a stack trace rather than a dead worker.',
    'workers = 0',
    '',
  ].join('\n');
}

/**
 * The arguments for a module test run.
 *
 * `--stop-after-init` is what makes this a validation rather than a server: Odoo
 * installs the modules, runs their tests, and exits with a status. Without it the
 * process would sit listening on a port on the customer's host.
 */
export function buildTestArguments(input: {
  readonly confPath: string;
  readonly databaseName: string;
  readonly modules: readonly string[];
}): string[] {
  if (input.modules.length === 0) {
    throw new Error('A validation run needs at least one module to install.');
  }

  return [
    '-c',
    input.confPath,
    '-d',
    input.databaseName,
    '-i',
    input.modules.join(','),
    '--test-enable',
    '--stop-after-init',
    '--log-level=test',
  ];
}
