#!/usr/bin/env python3
"""
Generate the Cartenz brand assets.

Run from the repository root:

    python3 infrastructure/brand/generate.py

Why a generator rather than hand-exported files: the wordmark is outlined
(text converted to paths) so a shipped SVG or PNG carries no dependency on a
font being installed wherever it is opened. Outlining by hand is
unmaintainable the moment a letter changes, and shipping a .ttf next to the
asset re-introduces the dependency the outlining removed. The numbers below
are the single source of truth; every asset in frontend/public/brand/ is an
output.

Outputs:
    mark.svg                 the pyramid alone, transparent
    wordmark.svg             "Cartenz / by LinkedERP", outlined, transparent
    lockup-horizontal.svg     mark beside the wordmark, transparent
    icon-<size>.png          square mark on the surface colour (favicons/PWA)
    lockup-on-<surface>.png  raster lockup, for places SVG cannot go
    favicon.ico              multi-resolution, for the browser tab
    manifest.webmanifest     web app manifest, for the install prompt
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

# --- Palette (kept in step by hand with frontend/tailwind.config.ts) ---------

SURFACE = "#0d1117"
SURFACE_RAISED = "#151b23"
CONTENT = "#e6edf3"
CONTENT_MUTED = "#9aa7b4"
ACCENT = "#c8102e"
ACCENT_DARK = "#8f0b20"

# --- Geometry ---------------------------------------------------------------
#
# The pyramid. Apex (32, 12); base y=48 with feet at x=10 and x=54, so the mass
# is centred with equal margins left and right and a deeper margin below, which
# rests it on an optical baseline instead of floating it.
APEX_X, APEX_Y = 32.0, 12.0
BASE_Y = 48.0
WEST_FOOT_X, EAST_FOOT_X = 10.0, 54.0

# The snow line, derived from the triangle rather than chosen: at y=23 the west
# edge is at x=25.28 and the east edge at x=38.72. That asymmetry about the
# ridge is what makes the cap read as a summit rather than a triangle balanced
# on a point — and it is why these two are computed, not typed.
SNOW_Y = 23.0


def _x_on_edge(y: float, foot_x: float) -> float:
    """The x where the horizontal line at `y` meets the edge from apex to foot."""
    t = (y - APEX_Y) / (BASE_Y - APEX_Y)
    return APEX_X + (foot_x - APEX_X) * t


SNOW_WEST_X = _x_on_edge(SNOW_Y, WEST_FOOT_X)
SNOW_EAST_X = _x_on_edge(SNOW_Y, EAST_FOOT_X)


def mark_faces(indent: str = "  ") -> str:
    """The three faces of the mark, as path elements."""
    west = (
        f"M{APEX_X:g} {APEX_Y:g} L{APEX_X:g} {BASE_Y:g} L{WEST_FOOT_X:g} {BASE_Y:g} Z"
    )
    east = (
        f"M{APEX_X:g} {APEX_Y:g} L{EAST_FOOT_X:g} {BASE_Y:g} L{APEX_X:g} {BASE_Y:g} Z"
    )
    cap = (
        f"M{APEX_X:g} {APEX_Y:g} L{SNOW_EAST_X:.2f} {SNOW_Y:g} "
        f"L{SNOW_WEST_X:.2f} {SNOW_Y:g} Z"
    )
    return (
        f'{indent}<path d="{west}" fill="{ACCENT}"/>\n'
        f'{indent}<path d="{east}" fill="{ACCENT_DARK}"/>\n'
        f'{indent}<path d="{cap}" fill="{CONTENT}"/>'
    )


MARK_SVG = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="Cartenz">
  <title>Cartenz</title>
  <!--
    The Cartenz mark: Cartensz Pyramid (Puncak Jaya, 4,884 m), the highest
    ground in Indonesia, which is where the name comes from. Two faceted faces
    meet at a ridge — the lit west face and the shadowed east face — and the
    snow cap is the summit itself.

    Generated by infrastructure/brand/generate.py; edit the geometry there, not
    here. The snow line is derived from the triangle: along the west edge
    y={SNOW_Y:g} lands at x={SNOW_WEST_X:.2f}, along the east edge at
    x={SNOW_EAST_X:.2f}.
  -->
{mark_faces()}
</svg>
'''


# --- Wordmark ---------------------------------------------------------------
#
# Outlined from Manrope ExtraBold (SIL OFL 1.1 — see Manrope-OFL.txt in this
# directory). The font is a build-time input only and is deliberately not
# copied into frontend/public/: the point of outlining is that the shipped
# asset needs no font.

WORD = "Cartenz"
BYLINE = "by LinkedERP"

FONT_PATH = Path(__file__).with_name("Manrope-ExtraBold.ttf")

WORD_SIZE = 46.0
WORD_TRACKING = 0.6
BYLINE_SIZE = 15.0
BYLINE_TRACKING = 2.4

# Manrope's cap height, as a fraction of em. Used to place the baseline so the
# visual mass sits where the box says it does.
CAP_HEIGHT = 0.72

LINE_GAP = 12.0
PAD = 4.0


def outline(text: str, size: float, tracking: float) -> tuple[str, float]:
    """
    Convert `text` to SVG path elements at `size`, adding `tracking` per glyph.

    Returns (path_markup, advance_width). Each glyph is emitted as its own
    path with a translate/scale transform, because font coordinates grow
    upwards and SVG's grow downwards — the negative y scale is that flip.
    """
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.ttLib import TTFont

    font = TTFont(str(FONT_PATH))
    upem = font["head"].unitsPerEm
    scale = size / upem
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]

    parts: list[str] = []
    cursor = 0.0

    for char in text:
        name = cmap.get(ord(char))
        if name is None:
            raise SystemExit(f"font has no glyph for {char!r}")

        pen = SVGPathPen(glyph_set)
        glyph_set[name].draw(pen)
        commands = pen.getCommands()

        if commands:
            parts.append(
                f'<path transform="translate({cursor:.3f} 0) '
                f'scale({scale:.6f} -{scale:.6f})" d="{commands}"/>'
            )

        cursor += hmtx[name][0] * scale + tracking

    font.close()
    # The cursor has trailing tracking on it; that is spacing, not width.
    return "\n    ".join(parts), cursor - tracking


def wordmark_svg(
    colour_word: str = CONTENT,
    colour_byline: str = CONTENT_MUTED,
    width: float | None = None,
    height: float | None = None,
    dx: float = 0.0,
    dy: float = 0.0,
) -> str:
    """
    The wordmark as a standalone SVG, or as a <g> fragment positioned at
    (dx, dy) inside a parent of the given width and height.
    """
    word_path, word_w = outline(WORD, WORD_SIZE, WORD_TRACKING)
    byline_path, byline_w = outline(BYLINE, BYLINE_SIZE, BYLINE_TRACKING)

    content_w = max(word_w, byline_w)
    content_h = WORD_SIZE * CAP_HEIGHT + LINE_GAP + BYLINE_SIZE

    if width is None:
        width = content_w + PAD * 2
    if height is None:
        height = content_h + PAD * 2

    word_baseline = WORD_SIZE * CAP_HEIGHT + PAD
    byline_baseline = word_baseline + LINE_GAP + BYLINE_SIZE * CAP_HEIGHT

    body = (
        f'  <g fill="{colour_word}" transform="translate({dx} {dy + word_baseline:.2f})">\n'
        f"    {word_path}\n"
        f"  </g>\n"
        f'  <g fill="{colour_byline}" transform="translate({dx + 1} {dy + byline_baseline:.2f})">\n'
        f"    {byline_path}\n"
        f"  </g>"
    )

    return body, width, height


def wordmark_document(
    colour_word: str = CONTENT, colour_byline: str = CONTENT_MUTED
) -> str:
    body, width, height = wordmark_svg(colour_word, colour_byline)
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:.2f} {height:.2f}" width="{width:.0f}" height="{height:.0f}" role="img" aria-label="Cartenz by LinkedERP">
  <title>Cartenz by LinkedERP</title>
  <!--
    Generated by infrastructure/brand/generate.py. The text is outlined
    (converted to paths) so this file renders identically anywhere, without
    Manrope being installed. Manrope is SIL OFL 1.1 — see Manrope-OFL.txt.
  -->
{body}
</svg>
'''


# --- Lockup -----------------------------------------------------------------
#
# Mark and wordmark side by side. The mark is optically centred against the
# two-line wordmark rather than aligned to its top or baseline: a triangle
# aligned to a baseline reads as falling over.

LOCKUP_MARK_SIZE = 76.0
LOCKUP_GAP = 20.0


def lockup_document(
    background: str | None = None,
    colour_word: str = CONTENT,
    colour_byline: str = CONTENT_MUTED,
) -> str:
    body, word_w, word_h = wordmark_svg(colour_word, colour_byline)

    mark_scale = LOCKUP_MARK_SIZE / 64.0
    height = max(LOCKUP_MARK_SIZE, word_h)
    width = LOCKUP_MARK_SIZE + LOCKUP_GAP + word_w

    mark_dy = (height - LOCKUP_MARK_SIZE) / 2
    word_dx = LOCKUP_MARK_SIZE + LOCKUP_GAP
    word_dy = (height - word_h) / 2

    mark = mark_faces(indent="    ")
    # mark_faces emits paths in the 0..64 space; scale and place them here.
    mark_block = (
        f'  <g transform="translate(0 {mark_dy:.2f}) scale({mark_scale:.6f})">\n'
        f"{mark}\n"
        f"  </g>"
    )

    background_rect = (
        f'  <rect width="{width:.2f}" height="{height:.2f}" fill="{background}"/>\n'
        if background
        else ""
    )

    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:.2f} {height:.2f}" width="{width:.0f}" height="{height:.0f}" role="img" aria-label="Cartenz by LinkedERP">
  <title>Cartenz by LinkedERP</title>
  <!--
    Generated by infrastructure/brand/generate.py. See mark.svg and
    wordmark.svg for why the wordmark is outlined.
  -->
{background_rect}{mark_block}
  <g transform="translate({word_dx:.2f} {word_dy:.2f})">
{body}
  </g>
</svg>
'''


# --- Icon -------------------------------------------------------------------
#
# The mark on a filled square. Favicons are small and a transparent mark
# disappears against a dark browser tab bar, so these carry the surface colour
# rather than transparency.

ICON_SIZES = [16, 32, 48, 64, 128, 180, 192, 256, 512]

# The mark is inset rather than filling the square: at 16px a triangle touching
# the edges reads as a blob, and the padding is what makes it read as a summit.
ICON_INSET = 0.12


def icon_svg(size: int, background: str = SURFACE, radius_ratio: float = 0.0) -> str:
    inset = size * ICON_INSET
    inner = size - inset * 2
    scale = inner / 64.0
    radius = size * radius_ratio

    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="{size}" height="{size}">
  <rect width="{size}" height="{size}" rx="{radius:.2f}" fill="{background}"/>
  <g transform="translate({inset:.2f} {inset:.2f}) scale({scale:.6f})">
{mark_faces(indent="    ")}
  </g>
</svg>
'''


# --- Rendering --------------------------------------------------------------
#
# sharp is used rather than a Python rasteriser: it bundles librsvg, so it is
# already present wherever the backend's dependencies are (it is a transitive
# dependency there), and it needs no system cairo. Invoked as a subprocess so
# this script stays pure-stdlib apart from fontTools.

SHARP_ROOT = None


def sharp_root() -> Path:
    global SHARP_ROOT
    if SHARP_ROOT is not None:
        return SHARP_ROOT

    for candidate in [
        Path(__file__).resolve().parents[2] / "node_modules",
        Path(__file__).resolve().parents[2] / "backend" / "node_modules",
        Path(__file__).resolve().parents[2] / "frontend" / "node_modules",
    ]:
        if (candidate / "sharp").is_dir():
            SHARP_ROOT = candidate
            return candidate

    raise SystemExit("sharp not found; run `npm install` in the repository root first")


def render(
    svg_path: Path,
    png_path: Path,
    size: int | None = None,
    width: int | None = None,
) -> None:
    """
    Rasterise `svg_path` to `png_path`.

    `size` forces an exact square pixel size; `width` scales to a pixel width
    and keeps the aspect ratio. The distinction matters: sharp's resize(w, h)
    defaults to fit=cover, which *crops* to fill the box, so resizing a
    landscape lockup to a square silently slices the mark off the left edge.
    """
    if size and width:
        raise SystemExit("pass either size or width, not both")

    if size:
        resize = f".resize({size}, {size}, {{ fit: 'contain' }})"
    elif width:
        resize = f".resize({{ width: {width} }})"
    else:
        resize = ""

    script = f"""
const sharp = require({json.dumps(str(sharp_root() / "sharp"))});
sharp({json.dumps(str(svg_path))}, {{ density: 384 }})
  {resize}
  .png({{ compressionLevel: 9 }})
  .toFile({json.dumps(str(png_path))})
  .then(() => process.exit(0))
  .catch((e) => {{ console.error(e.message); process.exit(1); }});
"""
    result = subprocess.run(
        ["node", "-e", script], capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        raise SystemExit(f"render failed for {png_path.name}: {result.stderr.strip()}")


def build_ico(png_paths: list[Path], ico_path: Path) -> None:
    """
    Assemble a multi-resolution .ico from rendered PNGs.

    Written by hand rather than shelled out to ImageMagick, which is not
    installed here: the ICO container is a 6-byte header plus a 16-byte
    directory entry per image plus the image bytes, and modern ICO accepts PNG
    payloads directly, so there is nothing to convert.
    """
    import struct

    images = []
    for path in png_paths:
        data = path.read_bytes()
        # PNG dimensions live in the IHDR chunk: bytes 16..24, big-endian.
        width = int.from_bytes(data[16:20], "big")
        height = int.from_bytes(data[20:24], "big")
        images.append((width, height, data))

    header = struct.pack("<HHH", 0, 1, len(images))

    offset = len(header) + 16 * len(images)
    entries = b""
    for width, height, data in images:
        entries += struct.pack(
            "<BBBBHHII",
            0 if width >= 256 else width,
            0 if height >= 256 else height,
            0,  # palette size
            0,  # reserved
            1,  # colour planes
            32,  # bits per pixel
            len(data),
            offset,
        )
        offset += len(data)

    ico_path.write_bytes(header + entries + b"".join(d[2] for d in images))


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    out = root / "frontend" / "public" / "brand"
    out.mkdir(parents=True, exist_ok=True)

    if not FONT_PATH.exists():
        print(f"missing font: {FONT_PATH}", file=sys.stderr)
        return 1

    written: list[Path] = []

    def write(name: str, content: str) -> Path:
        path = out / name
        path.write_text(content, encoding="utf-8")
        written.append(path)
        print(f"wrote {path.relative_to(root)}")
        return path

    # Vector sources.
    write("mark.svg", MARK_SVG)
    write("wordmark.svg", wordmark_document())
    write("lockup-horizontal.svg", lockup_document())

    # Square icons: transparency would vanish against a dark tab bar, so these
    # carry the surface colour.
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)

        ico_sources: list[Path] = []
        for size in ICON_SIZES:
            svg_path = tmp_dir / f"icon-{size}.svg"
            svg_path.write_text(icon_svg(size), encoding="utf-8")
            png_path = out / f"icon-{size}.png"
            render(svg_path, png_path, size)
            written.append(png_path)
            print(f"wrote {png_path.relative_to(root)}")
            if size in (16, 32, 48):
                ico_sources.append(png_path)

        # Raster lockups, for places SVG cannot go (email, slides, social).
        for label, background in [
            ("dark", SURFACE),
            ("raised", SURFACE_RAISED),
        ]:
            svg_path = tmp_dir / f"lockup-{label}.svg"
            svg_path.write_text(lockup_document(background=background), encoding="utf-8")
            png_path = out / f"lockup-on-{label}.png"
            render(svg_path, png_path, width=640)
            written.append(png_path)
            print(f"wrote {png_path.relative_to(root)}")

        ico_path = out / "favicon.ico"
        build_ico(ico_sources, ico_path)
        written.append(ico_path)
        print(f"wrote {ico_path.relative_to(root)}")

    manifest = {
        "name": "Cartenz",
        "short_name": "Cartenz",
        "description": "AI-assisted Odoo development platform by LinkedERP.",
        "start_url": "/dashboard",
        "display": "standalone",
        "background_color": SURFACE,
        "theme_color": ACCENT,
        "icons": [
            {"src": "/brand/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {
                "src": "/brand/icon-512.png",
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "any",
            },
            {
                "src": "/brand/icon-512.png",
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "maskable",
            },
        ],
    }
    path = out / "manifest.webmanifest"
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    written.append(path)
    print(f"wrote {path.relative_to(root)}")

    print(f"\n{len(written)} asset(s) written to {out.relative_to(root)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
